### ISSUE TITLE
How can I use this project

### ISSUE THREAD

**Issue by Elio-in-summer** [oysteinvolden/apriltag_state_estimation#1]
I also want to use april_tag+imu to estimate the UAV's pose
Or can you tell me where did you learn the theory about such fusion?
Thanks

**Comment by oysteinvolden** [comment]
The core algorithm is based on this Matlab implementation: https://github.com/cybergalactic/MSS/blob/master/GNC/ins_mekf_psi.m

Corresponding slides explaining the MEKF can be found here: https://www.fossen.biz/wiley/pdf/Ch14.pdf
Other more comprehensive references:
- https://link.springer.com/content/pdf/10.1007/978-1-4939-0802-8.pdf
- https://arxiv.org/pdf/1711.02508.pdf

I use this ROS wrapper of the AprilTag fiducial system: https://github.com/AprilRobotics/apriltag_ros
It is very useful since it allows us to define a tag bundle for increased accuracy and to avoid flip ambiguity.

Note that the code is customized to the onboard sensor suite, including IMU, camera-tag pose, and GNSS measurements. 
It is, however, straightforward to replace with your own sensors in the message handler class. Hence, for a simple implementation, look for the core functionality inside the run_mekf() function (which is called each time a new IMU message arrives) and interface with your own IMU sensor + e.g. AprilTag pose (or another aiding sensor).
